# Generated by Django 4.1.3 on 2022-11-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Localizacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_progra.area')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paciente', models.CharField(max_length=200)),
                ('Motivo_de_ingreso', models.CharField(max_length=200)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_progra.area')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('Sexo', models.CharField(max_length=200)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_progra.doctor')),
            ],
        ),
    ]
