# Generated by Django 4.1.3 on 2022-12-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_progra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENTES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Cliente', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=200)),
                ('Sexo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VEHICULOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('disponibilidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Area',
            new_name='EMPLEADOS',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Doctor',
        ),
        migrations.RenameField(
            model_name='empleados',
            old_name='Descripcion',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='empleados',
            old_name='Localizacion',
            new_name='Sexo',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Motivo_de_ingreso',
            new_name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
