# Generated by Django 4.1.3 on 2022-12-06 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_progra', '0002_clientes_vehiculos_rename_area_empleados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='Apellido',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='Apellido',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='clientes',
            name='Edad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='Telefono',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='Edad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='Telefono',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='empleado_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_progra.empleados'),
        ),
        migrations.AddField(
            model_name='registro',
            name='vehiculo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_progra.vehiculos'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='anio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Nombre_Cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Sexo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Sexo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='disponibilidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='Cliente_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_progra.clientes'),
        ),
    ]
